// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejtnvpmshcqydndxxonq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdG52cG1zaGNxeWRuZHh4b25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMzI0NTksImV4cCI6MjA5MDYwODQ1OX0.5iXpJuyIAKCKilGNzdaR635eVK43bw9khWyH1TnVwHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});

// When the tab/app comes back to foreground (mobile background, iframe focus loss, etc.)
// proactively refresh the session so a stale token doesn't kick the user to /auth.
if (typeof window !== 'undefined') {
  const refreshIfNeeded = async () => {
    try {
      const { data } = await supabase.auth.getSession();
      if (!data.session) return;
      const expiresAt = (data.session.expires_at ?? 0) * 1000;
      // Refresh if token expires within next 60 seconds
      if (expiresAt - Date.now() < 60_000) {
        await supabase.auth.refreshSession();
      }
    } catch {
      // ignore — onAuthStateChange will handle real failures
    }
  };

  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') refreshIfNeeded();
  });
  window.addEventListener('focus', refreshIfNeeded);
  window.addEventListener('online', refreshIfNeeded);
}
